server:
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/speeda
    username: developer
    password: developer
    driverClassName: com.mysql.jdbc.Driver
    
  cache:
    ehcache:
       config: classpath:ehcache.xml